# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'

# Created by: PyQt5 UI code generator 5.15.2

# WARNING: Any manual changes made to this file will be lost when pyuic5 is

# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_server(object):
    def setupUi(self, server):
        server.setObjectName("server")
        server.resize(400, 300)
        self.textEdit = QtWidgets.QTextEdit(server)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 191, 251))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(server)
        self.label.setGeometry(QtCore.QRect(60, 10, 72, 15))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(server)
        self.pushButton.setGeometry(QtCore.QRect(260, 100, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(server)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 170, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(server)
        QtCore.QMetaObject.connectSlotsByName(server)

    def retranslateUi(self, server):
        _translate = QtCore.QCoreApplication.translate
        server.setWindowTitle(_translate("server", "Dialog"))
        self.label.setText(_translate("server", "消息区域"))
        self.pushButton.setText(_translate("server", "OK"))
        self.pushButton_2.setText(_translate("server", "Cancel"))
